// <auto-generated />
namespace AmherstGolfClub.Migrations.GolfMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeYear : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeYear));
        
        string IMigrationMetadata.Id
        {
            get { return "201606231625095_removeYear"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
