// <auto-generated />
namespace AmherstGolfClub.Migrations.GolfMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DrawsSection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DrawsSection));
        
        string IMigrationMetadata.Id
        {
            get { return "201606281534038_DrawsSection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
