// <auto-generated />
namespace AmherstGolfClub.Migrations.GolfMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class readdStartonEvents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(readdStartonEvents));
        
        string IMigrationMetadata.Id
        {
            get { return "201606201634450_readdStartonEvents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
