// <auto-generated />
namespace AmherstGolfClub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adjustProductField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adjustProductField));
        
        string IMigrationMetadata.Id
        {
            get { return "201606061557490_adjustProductField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
